default: &default
  host: <%= Rails.application.secrets[:database][:host] %>
  adapter: mysql2
  database: <%= Rails.application.secrets[:database][:name] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  socket: /tmp/mysql.sock

development: *default
test: *default
production: *default

